os: windows

language: bash

before_install:
  - $([[ "${TRAVIS_BRANCH}" == "${TRAVIS_BRANCH}" ]]) &&
      travis_retry powershell Install-WindowsFeature Net-Framework-Core &&
      travis_retry choco install wixtoolset --version 3.11.1

install: skip  

script: skip